### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by StefanHub** [Krzysztof-Cieslak/vscode-elm#146]
For html element "li" it displays the wrong documentation:

![li wrong docu](https://user-images.githubusercontent.com/5167310/27260299-f21aca54-5428-11e7-8489-3dc2084f0912.png)

This is the documentation for Html.Attributes.list.

elm extension version 0.14.0

**Comment by andrewsdev** [comment]
This is due to the hover action only displaying the first record if multiple results are returned.  In the case of li there were 2, Html.Attributes.List and Html.li.  Attributes.List is in the first position and so was the only record returned.

I have checked in a fix to my branch which takes the results of a hover and filters them to only include exact matches to the hovered word (not a partial match ie "li" being a part of "list").

I'll include this in my next PR.

**Comment by StefanHub** [comment]
Great! Thanks!

**Comment by andrewsdev** [comment]
Please try out the latest version 0.14.1 it should fix this issue.

**Comment by StefanHub** [comment]
Yes, it works. Great!

Thanks!
