### ISSUE TITLE
'elm.formatOnSave' sends the cursor to the bottom of the file whenever it is run

### ISSUE THREAD

**Issue by mybuddymichael** [Krzysztof-Cieslak/vscode-elm#172]
### Platform
- Code Version 1.18.0
- macOS 10.12.6
- No other extensions installed besides elm.

### Config
```
{
    "editor.scrollBeyondLastLine": false,
    "workbench.colorTheme": "Default Light+",
    "workbench.panel.location": "right",
    "elm.formatOnSave": true
}
```

### Problem
Every time elm-format is run, the cursor is sent to the bottom of the file, instead of remaining in place.

**Comment by mybuddymichael** [comment]
I didn't realize there's an `editor.formatOnSave` setting. When I use that, there's no problem. Interesting.

**Comment by arian** [comment]
The `editor.formatOnSave` works too, but `elm.formatOnSave` is documented here: https://github.com/Krzysztof-Cieslak/vscode-elm#formatting-with-elm-format

and now sends the cursor to the bottom since VS Code 1.18.

So using `editor.formatOnSave` works as expected, the `elm.formatOnSave` option doesn't :worried:
